name: asmita_flutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.0+1
  firebase_core: ^0.4.3+1
  firebase_analytics: ^5.0.9
  firebase_messaging: ^6.0.9
  animated_text_kit: ^1.3.1
  modal_progress_hud: ^0.1.3
  url_launcher: ^5.4.1
  pdf_viewer_plugin: ^1.0.0+2
  path_provider: ^1.5.1
  http:
  intl: ^0.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/nunitosans_black.ttf